from os.path import join
import itertools
import pandas as pd
from snakebids import bids

configfile: 'config/config.yml'

if config['run_cohort'] == None:
    cohorts = config['cohorts']
else:
    cohorts = [config['run_cohort']]

#subjects is a dict, indexed by the cohort
#load participants.tsv file, and strip off sub- from participant_id column
subjects = dict()
all_subjects = list()
for cohort in config['cohorts']:
    subjects[cohort] = [ s.strip('sub-') for s in pd.read_table(config['participants_tsv'][cohort]).participant_id.to_list() ] 
    all_subjects = all_subjects + subjects[cohort]

#get channels using keys in in_images
channels = list(config['in_images'].keys())

#need this to make sure iterations don't go below 0!
wildcard_constraints:
    iteration="[0-9]+",
    cohort="[a-zA-Z0-9]+"



rule all_iter:
    input:
         expand('results/cohort-{cohort}/iter_{iter}/template_{channel}.nii.gz',cohort=cohorts,channel=channels,iter=config['max_iters'])



rule all_subj_seg_atlas:
    input:
        expand('results/atlasseg-{std_template}/sub-{subject}/sub-{subject}_desc-brain_mask.nii.gz',subject=all_subjects,std_template=config['std_template_name']),
        expand('results/atlasseg-{std_template}/sub-{subject}/sub-{subject}_label-{label}_desc-{desc}_probseg.nii.gz',subject=all_subjects,std_template=config['std_template_name'],label=config['tissue_3tt'].keys(),desc='3tt'),
        expand('results/atlasseg-{std_template}/sub-{subject}/sub-{subject}_label-{label}_desc-{desc}_probseg.nii.gz',subject=all_subjects,std_template=config['std_template_name'],label=config['tissue_6tt'].keys(),desc='6tt'),


rule all_composite_warps:
    input: expand('results/composite/sub-{subject}_to-{template}_via-cohort_{warptype}.nii.gz',\
                    template=config['std_template_name'],\
                    warptype=['CompositeWarp','CompositeInverseWarp'],\
                    subject=all_subjects)


include: 'rules/preproc_t2.smk'
include: 'rules/ants_template.smk'
include: 'rules/cohort_template_to_std.smk'

